### ISSUE TITLE
Critical: module 'beluga' has no attribute 'metrics'

### ISSUE THREAD

**Issue by CosmoSt4r** [datasciencewithdaniel/beluga#18]
I can't import module this way:
```py
import beluga-ml
```
because it's invalid syntax. You have to change '-' to '_' if you want it to work properly.

I can import library like this:
```py
import beluga
```
but when I try to call any method it raises an error:
```py
beluga.metrics.f1([1, 2, 3], [1, 2, 3])
>>> AttributeError: module 'beluga' has no attribute 'metrics'
```
The way I fixed it: in **\_\_init\_\_.py** added line "from . import metrics"

Steps to reproduce:
1. Open Terminal
2. ```pip install beluga-ml```
3. ```import beluga```
4. ```beluga.metrics.recall([], [])```
5. ```AttributeError: module 'beluga' has no attribute 'metrics'```

**Comment by danielchegwidden** [comment]
Fixed in release [1.0.1](https://github.com/datasciencewithdaniel/beluga/releases/tag/v1.0.1)
